[package]
name = "iota-lib-rs"
version = "0.0.4"
authors = ["Nathan Jaremko <nathan@jaremko.ca>"]
description = "A rust implementation of the IOTA API"
license = "MIT"
readme = "README.md"
keywords = ["iota", "api"]
repository = "https://github.com/njaremko/iota-lib-rs"

[dependencies]
ascii = "0.9"
crunchy = "0.1"
error-chain = "0.11"
failure = "0.1"
lazy_static = "1.0"
num_cpus = "1.8"
rand = "0.5"
rayon = "1.0"
regex = "1.0"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "kerl_benchmark"
harness = false

[[bench]]
name = "pow_benchmark"
harness = false
