[package]
name = "iota-wallet"
version = "0.2.0"
authors = ["IOTA Stiftung"]
edition = "2021"
description = "A stateful package for IOTA value transactions"
documentation = "https://wiki.iota.org/wallet.rs/welcome"
homepage = "https://www.iota.org/"
repository = "https://github.com/iotaledger/wallet.rs"
license = "Apache-2.0"
keywords = ["iota", "wallet", "transaction"]
categories = ["cryptography::cryptocurrencies"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
async-trait =  { version ="0.1.51", default-features = false }
futures =  { version = "0.3.17", default-features = false }
getset =  { version = "0.1.1", default-features = false }
hex =  { version = "0.4.3", default-features = false }
iota-client = { git = "https://github.com/iotaledger/iota.rs", rev = "e11be4d06edabd618c949cf8c83bcad9dd584375", default-features = false, features = ["async"] }
iota-crypto = { version = "0.7.0", default-features = false, features = ["std", "random", "sha", "pbkdf", "hmac", "bip39", "bip39-en", "chacha", "blake2b", "slip10"] }
log = { version = "0.4.14", default-features = false }
once_cell = { version = "1.8.0", default-features = false, features = ["std"] }
serde = { version = "1.0.130", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.68", default-features = false }
thiserror =  { version = "1.0.29", default-features = false }
tokio = { version = "1.12.0", default-features = false }
url = { version = "2.2.2", default-features = false, features = ["serde"] }

# storage
rocksdb = { git="https://github.com/iotaledger/rust-rocksdb", rev = "d2c579660e6c72ec1f14f0f2781cef5e3171d380", default-features = false, features = ["lz4"], optional = true }

# stronghold
# iota_stronghold = { version = "0.4.1", default-features = false }
# riker = { version = "0.4.2", default-features = false }
# slog = { version = "2.7.0", default-features = false }

[features]
# only default for now, should later be replaced by stronghold since stronghold is more secure
default = ["mnemonic", "events", "storage"]
ledger-nano = ["iota-client/ledger"]
ledger-nano-simulator = ["iota-client/ledger"]
# stronghold = []
storage = ["rocksdb"]
# actor = []
events = []
mnemonic = []
