[package]
name = "iota-wallet"
version = "0.1.0"
authors = ["Lucas Nogueira <lucas.nogueira@iota.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bee-signing = { git = "https://github.com/iotaledger/bee" }
bee-crypto = { git = "https://github.com/iotaledger/bee" }
bee-transaction = { git = "https://github.com/Alex6323/bee-p" }
bee-ternary = { git = "https://github.com/iotaledger/bee", features = ["serde1"] }
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
getset = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.4"
kv = "0.20"
#iota-client-mock = { path = "./iota-client-mock/" }
iota-core = { git = "https://github.com/iotaledger/iota.rs", rev = "5eb9fd1" }
url = { version = "2.1", features = [ "serde" ] }
tokio = "0.2"
rand = "0.3"

# sql
rusqlite = { version = "0.23", optional = true }

# stronghold
vault = { git = "https://github.com/iotaledger/stronghold.rs/", optional = true, rev = "a81191f" }
crypto = { git = "https://github.com/iotaledger/stronghold.rs/", optional = true, rev = "a81191f" }
random = { git = "https://github.com/iotaledger/stronghold.rs/", optional = true, rev = "a81191f" }
snapshot = { git = "https://github.com/iotaledger/stronghold.rs/", optional = true, rev = "a81191f" }
primitives = { git = "https://github.com/iotaledger/stronghold.rs/", optional = true, rev = "a81191f" }
bincode = { version = "1.3.1", optional = true }

[features]
stronghold = ["vault", "crypto", "random", "snapshot", "primitives", "bincode"]
sqlite = ["rusqlite"]
