[package]
name = "iota-lib-rs"
version = "0.0.1"
authors = ["Nathan Jaremko <nathan@jaremko.ca>"]
description = "A rust implementation of the IOTA API"
license = "MIT"
readme = "README.md"
keywords = ["iota", "api"]
repository = "https://github.com/njaremko/iota-lib-rs"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
lazy_static = "1.0"
ascii = "0.9"
error-chain = "0.11"
tiny-keccak = "1.4"
regex = "1.0"
rand = "0.5"
reqwest = "0.8"
failure = "0.1"
num-bigint = "0.2"
num-traits = "0.2"
num-integer = "0.1"