[package]
name = "iota-lib-rs"
version = "0.1.0"
authors = ["Nathan Jaremko <njaremko@gmail.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
lazy_static = "1.0"
ascii = "0.9.0"
error-chain = "0.11"
crunchy = "0.1.6"
tiny-keccak = "1.4"