[package]
name = "iota-constants"
version = "0.2.0"
authors = ["Nathan Jaremko <nathan@jaremko.ca>"]
edition = "2018"
description = "Constants used by Iota"
license = "MIT"

[lib]
name = "iota_constants"
path = "lib.rs"

[dependencies]